### ISSUE TITLE
TabBarView

### ISSUE THREAD

**Issue by AlexZd** [YorkUI/Pageboy#10]
Hello,
Is there way to make navigation same as here https://github.com/MerrickSapsford/MSSTabbedPageViewController ?

**Comment by MerrickSapsford** [comment]
Hi,

I'm currently working on a full blown replacement for `MSSTabbedPageViewController`, which should be available in the next few weeks. `Pageboy` is simply the page view controller component that the replacement framework will utilise. 

I've just decided to split them up this time round.

Cheers

**Comment by msaps** [comment]
[Tabman](https://github.com/yorkui/tabman) is now available as a full blow replacement for `MSSTabbedPageViewController`. 😄
